apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boundary

bases:
- ../../base/

commonLabels:
  app.kubernetes.io/instance: service

secretGenerator:
- name: boundary-controller-secret
  literals:
  - BOUNDARY_POSTGRES_URL=postgresql://boundary:Password!123@boundary-postgres-svc:5432/postgres?sslmode=disable

configMapGenerator:
- name: boundary-controller-configmap
  files:
  - config/config.hcl

images:
- name: boundary-controller
  newTag: '0.13.1'
  newName: hashicorp/boundary
