kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: svc-cluster
nodes:
- role: control-plane
  image: kindest/node:v1.25.3
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  # extraPortMappings:
  # - containerPort: 80
  #   hostPort: 80
  #   protocol: TCP
  extraMounts:
  - hostPath: ~/$USER/kind-volumes
    containerPath: /home/docker/volumes/svc
