apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boundary

resources:
- namespace.yaml                #1
- postgres/deployment.yaml      #1
- postgres/service.yaml         #1
- boundary-migrator/job.yaml    #2
- boundary/deployment.yaml      #3
- boundary/service.yaml         #3

configMapGenerator:
- name: postgres-configmap
  literals:
  - POSTGRES_USER=admin-boundary
  - POSTGRES_PASSWORD=Password!123

secretGenerator:
- name: boundary-secret
  literals:
  - BOUNDARY_POSTGRES_URL=postgresql://admin-boundary:Password!123@postgres-svc:5432/postgres?sslmode=disable

commonLabels:
  kubernetes.io/environment: dev
