apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boundary

bases:
- ../../base/

commonLabels:
  app.kubernetes.io/instance: service

secretGenerator:
- name: boundary-migrator-secret
  literals:
  - BOUNDARY_POSTGRES_URL=postgresql://boundary:Password!123@boundary-postgres-svc:5432/postgres?sslmode=disable

images:
- name: boundary-migrator
  newTag: latest
  newName: hashicorp/boundary
