apiVersion: batch/v1
kind: Job
metadata:
  name: boundary-migrator
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 43200 # 12 hours
  parallelism: 1
  completions: 1
  ttlSecondsAfterFinished: 86400 #1 day
  template:
    metadata:
      name: boundary-migrator
      labels:
        app: boundary
    spec:
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      containers:
      - name: boundary-migrator
        image: boundary-migrator
        envFrom:
        - secretRef:
            name: boundary-migrator-secret
        command:
        - boundary
        - database
        - init
        - -config
        - /boundary/config.hcl
        resources:
          requests:
            cpu: 256m
            memory: 384Mi
          limits:
            cpu: 256m
            memory: 384Mi
