apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boundary

resources:
- job.yaml

commonLabels:
  app.kubernetes.io/name: boundary
  app.kubernetes.io/managed-by: DionathanChrys