kind: Deployment
apiVersion: apps/v1
metadata:
  name: foo-postgres
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      db: foo-postgres
  template:
    metadata:
      labels:
        db: foo-postgres
    spec:
      containers:
      - name: foo-postgres
        image: foo-postgres
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        ports:
        - name: db
          containerPort: 5432
        envFrom:
        - configMapRef:
            name: foo-postgres-configmap
        livenessProbe:
          httpGet:
            path: /
            port: 5432
            scheme: HTTP
          initialDelaySeconds: 300
          timeoutSeconds: 10
          periodSeconds: 300
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - name: database-postgres
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: database-postgres
        hostPath:
          path: /home/docker/volumes/dev/foo-postgres
          type: DirectoryOrCreate
