apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-pool-dev
  namespace: metallb-system
spec:
  addresses:
  - 192.168.222.5-192.168.222.5
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
