kind: Deployment
apiVersion: apps/v1
metadata:
  name: boundary
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: boundary
  template:
    metadata:
      labels:
        app: boundary
    spec:
      containers:
      - name: boundary
        image: hashicorp/boundary
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        envFrom:
        - secretRef:
            name: boundary-secret
        ports:
        - name: api
          containerPort: 9200
        - name: cluster
          containerPort: 9201
        - name: proxy
          containerPort: 9202
        livenessProbe:
          httpGet:
            path: /
            port: 9200
            scheme: HTTP
          initialDelaySeconds: 300
          timeoutSeconds: 10
          periodSeconds: 300
          successThreshold: 1
          failureThreshold: 5
