apiVersion: v1
kind: Service
metadata:
  name: boundary-svc
spec:
  ports:
  - port: 9200
    name: api/ui
    targetPort: 9200
    protocol: TCP
  - port: 9201
    name: cluster
    targetPort: 9201
    protocol: TCP
  - port: 9202
    name: proxy
    targetPort: 9202
    protocol: TCP
  selector:
    app: boundary