apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: foo-app

bases:
- ../../base/

commonLabels:
  app.kubernetes.io/environment: production

configMapGenerator:
- name: foo-postgres-configmap
  literals:
  - POSTGRES_USER=foo-app
  - POSTGRES_PASSWORD=Password@prd

images:
- name: foo-postgres
  newTag: '13'
  newName: postgres
