apiVersion: v1
kind: Service
metadata:
  name: boundary-worker-svc
spec:
  type: NodePort
  ports:
  - port: 9202
    name: proxy
    targetPort: 9202
    protocol: TCP
    nodePort: 32202
  selector:
    app: boundary-worker
