apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boundary

bases:
- ../../base/

commonLabels:
  app.kubernetes.io/environment: service

configMapGenerator:
- name: boundary-postgres-configmap
  literals:
  - POSTGRES_USER=boundary
  - POSTGRES_PASSWORD=Password!123

images:
- name: boundary-postgres
  newTag: '12'
  newName: postgres
